### ISSUE TITLE
Feature - Is In Array Comparison

### ISSUE THREAD

**Issue by JamesWiresmith** [WiresmithTech/VITAC#1]
Comparison function that tells you if the array contains the item.

**Comment by kosist** [comment]
Couldn't ibe solved by simple Pass/Fail assert, and Empty Array? function?

**Comment by JamesWiresmith** [comment]
Not that there is anything in the array but if I have array [1, 2, 3] we test if 2 is in it (pass) or if 5 is in it (fail).

So it would likely be a search 1D array and pass if not -1.

**Comment by kosist** [comment]
Thank you, sorry - I understood it wrong, my fault; in this case it would be extremely handy function, I guess. Maybe it's offtopic here, but what version of LV should one use, to contribute to this repository? LV2013 SP1, as for VI Tester repository, or you use something else?

**Comment by JamesWiresmith** [comment]
The library is developed in 2015 SP1 so please use that version for contributions

**Comment by JamesWiresmith** [comment]
Completed in pull request #4
