### ISSUE TITLE
Custom report message input is missing

### ISSUE THREAD

**Issue by kosist** [WiresmithTech/VITAC#17]
This is more a question, than an issue. But, just now I've realized that "Custom report message" input, which is present in base assert functions from JKI is missing for VITAC functions... Maybe, it worth to add? Now I have test case with 4 comparisons of arrays (does not make sense to separate it to different test cases, b/c code module has 4 output arrays), and custom message in case of error could help to see at least for each result I've got the failure...
Thanks a lot in advance for a reply,
Sincerely, Ivan.

**Comment by JamesWiresmith** [comment]
Hi Ivan,

Makes perfect sense. I'll pencil this in for the next update.

Cheers,
James
