### ISSUE TITLE
Pass If Equal String.vi, "One String Is Empty" message

### ISSUE THREAD

**Issue by kosist** [WiresmithTech/VITAC#26]
Now "One String Is Empty" message is returned when any of input strings (Expected or Actual) is empty. 

But maybe it will be better to change it in a way that "String Is Empty" message will be just in case when "Actual" string is empty. Because our test could be designed in a way that it expects "Actual" string to be empty, so empty Expected string should not be a warning to user.

**Comment by JamesWiresmith** [comment]
Yes agreed - this message has also caused me confusion in the past anyway so I would agree with the change.
