### ISSUE TITLE
Broken templates from functions palette

### ISSUE THREAD

**Issue by kosist** [WiresmithTech/VITAC#6]
While dropping templates from functions palette (Addons -> VITAC -> Templates-> Given When Then or Test Event Response), there is error during loading of some dependencies (String Equality Test Case.lvclass), as on  the screenshot.
Seems, that either the VI is in another location, or it is not included to package at all...
I've tried it in LabVIEW 2016 f5; VITAC v1.1.1.17.
Seems, that it was solved already in some previous commit, but looks like it is still present in the released version.

![dependency loading](https://user-images.githubusercontent.com/1911151/36785029-be698bd8-1c81-11e8-9b5e-1c0f3aa8009d.png)

**Comment by JamesWiresmith** [comment]
Unfortunately the previous fix didn't work properly (or only worked once) so I still need to get to the bottom of this.

**Comment by kosist** [comment]
Seems, that with new build the issue is solved. I've checked it with LabVIEW 2016 and 2017, template is dropped as it should.
